---

# - name: SSH | ensure ssh private key is present
#   copy: content="{{ ssh_private_key}}" dest="{{ ansible_env.HOME }}/.ssh/id_rsa"

# - name: SSH | ensure ssh public key is present
#   copy: content="{{ ssh_public_key }}" dest="{{ ansible_env.HOME }}/.ssh/id_rsa.pub"


- name: DOT | retrieve dotfiles
  git: repo={{ dotfiles_repository }} dest="{{ ansible_env.HOME }}/.dotfiles" accept_hostkey=true version=stow update=no

- name: ZSH | get path to zsh
  shell: which zsh
  register: zsh_path
  changed_when: false

- name: configure user account
  user: name={{ ansible_env.USER }} shell={{ zsh_path.stdout }} groups={{ user_groups }}
  become: true


- name: MacOSX
  include: "os_x.yml"
  when: ansible_distribution == "MacOSX"
