---



- name: SSH | ensure ssh private key is present
  copy: content="{{ ssh_private_key}}" dest="{{ ansible_env.HOME }}/.ssh/id_rsa"

- name: SSH | ensure ssh public key is present
  copy: content="{{ ssh_public_key }}" dest="{{ ansible_env.HOME }}/.ssh/id_rsa.pub"


- name: DOT | retrieve dotfiles
  git: repo={{ dotfiles_repository }} dest="{{ ansible_env.HOME }}/.dotfiles" accept_hostkey=true version=stow update=no

- name: ZSH | set default shell
  shell: "chsh -u {{ ansible_env.USER }} -s /bin/zsh"



# Disable CapsLock
# http://apple.stackexchange.com/questions/13598/updating-modifier-key-mappings-through-defaults-command-tool
#
# Apparently not necessary when running Seil
#
# - name: Keyboard | determine keyboard VendorID
#   shell: ioreg -n IOHIDKeyboard -r | awk '$2 == "\"VendorID\"" { print $4 }'
#   register: keyboard_vendor_id
#   changed_when: false
#
# - name: Keyboard | determine keyboard ProductID
#   shell: ioreg -n IOHIDKeyboard -r | awk '$2 == "\"ProductID\"" { print $4 }'
#   register: keyboard_product_id
#   changed_when: false
#
# - debug: var=keyboard_vendor_id
# - debug: var=keyboard_product_id
#
# - name: Keyboard | disable CapsLock modifier
#   osx_defaults:


- name: Keyboard | get Seil configuration
  shell: "{{ seil_path }}/seil export"
  register: keyboard_seil
  changed_when: false

- name: Keyboard | Seil enable CapsLock
  shell: "{{ seil_path }}/seil set enable_capslock 1"
  when: "'enable_capslock 1' not in keyboard_seil.stdout"
  notify: seil relaunch

- name: Keyboard | Seil set CapsLock to F10
  shell: "{{ seil_path }}/seil set keycode_capslock 109"
  when: "'keycode_capslock 109' not in keyboard_seil.stdout"
  notify: seil relaunch
