---

# - name: SSH | ensure ssh private key is present
#   copy: content="{{ ssh_private_key}}" dest="{{ ansible_env.HOME }}/.ssh/id_rsa"

# - name: SSH | ensure ssh public key is present
#   copy: content="{{ ssh_public_key }}" dest="{{ ansible_env.HOME }}/.ssh/id_rsa.pub"


- name: DOT | retrieve dotfiles
  git: repo={{ dotfiles_repository }} dest="{{ ansible_env.HOME }}/.dotfiles" accept_hostkey=true version=stow update=no

- name: ZSH | set default shell
  shell: "chsh -u {{ ansible_env.USER }} -s /bin/zsh"


- name: MacOSX
  include: "os_x.yml"
  when: ansible_distribution == "MacOSX"
