---


- name: Homebrew
  include: "homebrew.yml"
  when: ansible_distribution == "MacOSX"

- name: ensure packages are present
  apt: name={{ item }} state=present
  with_items: "{{ packages }}"
  when: ansible_distribution == "Ubuntu"
  become: true


- name: ZSH | get pretzo
  git: repo="https://github.com/sorin-ionescu/prezto.git" dest="{{ ansible_env.HOME }}/.zprezto" update=no
