---


- name: Homebrew
  include: "homebrew.yml"
  when: ansible_distribution == "MacOSX"


- name: ZSH | get pretzo
  git: repo="https://github.com/sorin-ionescu/prezto.git" dest="{{ ansible_env.HOME }}/.zprezto" update=no
