---


- name: Homebrew
  include: "homebrew.yml"
  when: ansible_distribution == "MacOSX"

- name: ensure packages are present (Debian)
  apt: name={{ item }} state=present
  with_items: "{{ packages }}"
  when: ansible_distribution == "Ubuntu"
  become: true

- name: ensure packages are present (Arch)
  pacman: name={{ item }} state=present
  with_items: "{{ packages }}"
  when: ansible_distribution == "Antergos" or ansible_distribution == "Arch"
  become: true



- name: install AUR packages
  when: ansible_distribution == "Antergos" or ansible_distribution == "Arch"
  include: aur/pkg.yml 
  with_items: "{{ aur_packages }}"


- name: ZSH | get pretzo
  git: repo="https://github.com/sorin-ionescu/prezto.git" dest="{{ ansible_env.HOME }}/.zprezto" update=no
