---

- name: ensure homebrew taps are set
  homebrew_tap: tap={{ item }} state=present
  with_items: "{{ homebrew_taps }}"


- name: ensure homebrew packages are present
  homebrew: name={{ item }} state=present
  with_items: "{{ homebrew_packages }}"


- name: ensure homebrew casks are present
  homebrew_cask: name={{ item }} state=present
  with_items: "{{ homebrew_casks }}"



- name: ZSH | get pretzo
  git: repo="https://github.com/sorin-ionescu/prezto.git" dest="{{ ansible_env.HOME }}/.zprezto" update=no
